# -*- coding: utf-8 -*-
"""Loan_regressor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1txkMxnqyULoET_qtpTHnAanfYm9cqBbr
"""

from fastapi import FastAPI
import joblib
import numpy as np
import pandas as pd
from sklearn.preprocessing import PolynomialFeatures, StandardScaler

# --- Create the API application ---
app_regressor = FastAPI(title="Pessimistic Return Regressor API")

# --- Load the saved model, polynomial features transformer, and scaler ---
regressor_model = joblib.load("Pessimistic_Return_model.pkl")
poly_transformer = joblib.load("poly_features.pkl")
poly_scaler = joblib.load("scaler_poly_features.pkl")

# --- Get original feature names for consistent input order ---
# Assuming X_train_reg.columns contains the original feature names
original_reg_features = joblib.load('X_train_reg.pkl').columns

# --- Endpoint 1: Home page ---
@app_regressor.get("/regressor/")
def home_regressor():
    return {"message": "Pessimistic Return Regressor API is running"}

# --- Endpoint 2: Prediction ---
@app_regressor.post("/regressor/predict")
def predict_return_pessimistic(data: dict):
    # Ensure the input data contains all expected original features
    try:
        original_features_array = np.array([[data[feature] for feature in original_reg_features]])
    except KeyError as e:
        return {"error": f"Missing feature in input data: {e}"}, 400

    # Transform original features into polynomial features
    poly_features = poly_transformer.transform(original_features_array)

    # Scale the polynomial features
    scaled_poly_features = poly_scaler.transform(poly_features)

    # Use the model to predict the pessimistic return
    predicted_return = regressor_model.predict(scaled_poly_features)[0]

    return {"predicted_return_pessimistic": round(float(predicted_return), 4)}